simulation_rate: 50.0
clock_rate: 50.0
realtime_factor: 1.0

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

collisions:
  enabled: false
  crash: false

  # if crash==false, then the collisions are elastic
  rebounce: 100.0

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: true

  bounds:
    x: 0.0
    y: 15.0
    z: 6.0

ground:
  enabled: true
  z: 0.0 # [m]

uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
]

uav1:
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 1.0
    heading: 0

uav2:
  type: "x500"
  spawn:
    x: 4.0
    y: 0.0
    z: 2.0
    heading: 0

uav3:
  type: "x500"
  spawn:
    x: 8.0
    y: 0.0
    z: 3.0
    heading: 0

uav4:
  type: "x500"
  spawn:
    x: 12.0
    y: 0.0
    z: 4.0
    heading: 0

uav5:
  type: "x500"
  spawn:
    x: 16.0
    y: 0.0
    z: 5.0
    heading: 0

uav6:
  type: "x500"
  spawn:
    x: 20.0
    y: 0.0
    z: 6.0
    heading: 0

uav7:
  type: "x500"
  spawn:
    x: 24.0
    y: 0.0
    z: 7.0
    heading: 0

uav8:
  type: "x500"
  spawn:
    x: 28.0
    y: 0.0
    z: 5.0
    heading: 0

uav9:
  type: "x500"
  spawn:
    x: 32.0
    y: 0.0
    z: 3.0
    heading: 0

uav10:
  type: "x500"
  spawn:
    x: 36.0
    y: 0.0
    z: 1.0
    heading: 0
